<?xml version="1.0"?>
<!-- Balancing Double Pendulum -->
<robot name="double_pendulum" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1.0" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="0.2" /> <!-- Link 1 -->
  <xacro:property name="height2" value="1.1" /> <!-- Link 2 -->
  <xacro:property name="height3" value="1.1" /> <!-- Link 3 -->
  
  <xacro:property name="foot_height" value="0.05" /> <!-- Foot dimensions -->
  <xacro:property name="foot_width" value="0.5" /> 

  <xacro:property name="axel_offset" value="0.05" /> <!-- How far keep joints away from each other -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find double_pendulum_description)/urdf/double_pendulum.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find double_pendulum_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot foot to the world -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="foot"/>
  </joint>

  <!-- Foot Link-->
  <link name="foot">
    <collision>
      <origin xyz="0 0 ${foot_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${foot_width} ${foot_width} ${foot_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${foot_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${foot_width} ${foot_width} ${foot_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${foot_height/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
    <inertia
        ixx="${mass / 12.0 * (foot_width*foot_width + foot_height*foot_height)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (foot_height*foot_height + foot_width*foot_width)}" iyz="0.0"
        izz="${mass / 12.0 * (foot_width*foot_width + foot_width*foot_width)}"/>
    </inertial>
  </link>

  <joint name="foot_joint" type="fixed">
    <parent link="foot"/>
    <child link="link1"/>
    <origin xyz="0 -${width} ${foot_height}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
    <inertia
        ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 ${width} ${height1 - axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.5"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2">
    <collision>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height2+axel_offset}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <!-- inertias copied from matlab model-->
      <inertia
        ixx="0.3345833333333" ixy="0.0" ixz="0.0"
        iyy="0.3345833333333" iyz="0.0"
        izz="0.0025"/>
    </inertial>
  </link>

  <joint name="joint2" type="continuous">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 ${width} ${height2 - axel_offset*2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.5"/>
  </joint>

  <!-- Top Link -->
  <link name="link3">
    <collision>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height3}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="0.3345833333333" ixy="0.0" ixz="0.0"
        iyy="0.3345833333333" iyz="0.0"
        izz="0.0025"/>
    </inertial>
  </link>

  <!-- Motors so we can actuate the joints -->
  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
